<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Product extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            ['id' => 1, 'picture_Product' => 'product-01.jpg', 'name_Product' => 'Esprit Ruffle Shirt', 'price_Product' => 16.64, 'size_Product' => 'S', 'color_Product' => 'White', 'weight_Product' => '0.29 kg', 'dimensisons_Product' => '110 x 33 x 100 cm', 'materials_Product' => 'spandex', 'description_Product' => 'Stay cool and dry in the Russell Athletic Dri-Power Core Performance Long Sleeve Tee while in the gym, on the court, or on the field. This men is long sleeve T-shirt has a relaxed fit for complete comfort.'],
            ['id' => 2, 'picture_Product' => 'product-02.jpg', 'name_Product' => 'Herschel supply', 'price_Product' => 35.31, 'size_Product' => 'M', 'color_Product' => 'White', 'weight_Product' => '0.35 kg', 'dimensisons_Product' => '100 x 23 x 90 cm', 'materials_Product' => '60% cotton', 'description_Product' => 'This boat-neck top makes a statement in seaworthy stripes and a feminine cut, slit at the hem for smooth movement.'],
            ['id' => 3, 'picture_Product' => 'product-03.jpg', 'name_Product' => 'Only Check Trouser', 'price_Product' => 25.50, 'size_Product' => 'L', 'color_Product' => 'Blue', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '98% Cotton', 'description_Product' => 'Made with Organic Content Standard (OCS) 100 certified organic cotton and certified carbon neutral by ClimatePartner. Learn about our third party sustainability certifications below.'],
            ['id' => 4, 'picture_Product' => 'product-04.jpg', 'name_Product' => 'Classic Trench Coat', 'price_Product' => 75.00, 'size_Product' => 'S', 'color_Product' => 'Brown', 'weight_Product' => '0.55 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '50% Cotton, 40% Polyester, 10% Nylon', 'description_Product' => 'Focused on creating affordable, high-quality, and long-lasting everyday clothing you can rely on. Our line of women is apparel includes cashmere sweaters, fleece and down jackets, and more, including plus-size options. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort.'],
            ['id' => 5, 'picture_Product' => 'product-05.jpg', 'name_Product' => 'Front Pocket Jumper', 'price_Product' => 34.75, 'size_Product' => 'L', 'color_Product' => 'Gray', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '77% Cotton, 21% Polyester', 'description_Product' => 'Made with Organic Content Standard (OCS) 100 certified organic cotton and certified carbon neutral by ClimatePartner. Learn about our third party sustainability certifications below.These are the double-front denim bibs you will be wearing for years to come. Bring on the mud, paint, and grass stains.'],
            ['id' => 6, 'picture_Product' => 'product-06.jpg', 'name_Product' => 'Vintage Inspired Classic', 'price_Product' => 93.20, 'size_Product' => '28mm', 'color_Product' => 'Black', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '3 x 3 x 3 cm', 'materials_Product' => 'metal', 'description_Product' => 'Create the lifestyle that gives you confidence with the help of our sports smartwatch for women and men. With smart features like music controls, weather forecast and push notifications – you have everything you need to come back stronger.'],
            ['id' => 7, 'picture_Product' => 'product-07.jpg', 'name_Product' => 'Shirt in Stretch Cotton', 'price_Product' => 52.66, 'size_Product' => 'L', 'color_Product' => 'Brown', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Cotton', 'description_Product' => 'We listen to customer feedback and fine-tune every detail to ensure our clothes are more comfortable, higher quality, and longer lasting—at affordable prices for the whole family.'],
            ['id' => 8, 'picture_Product' => 'product-08.jpg', 'name_Product' => 'Pieces Metallic Printed', 'price_Product' => 18.96, 'size_Product' => 'M', 'color_Product' => 'White', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '60% Polyester, 30% Cotton, 10% Rayon', 'description_Product' => 'Love today is trendy graphic tees do not miss out on this one. It is soft, feminine, flattering...and available in your pick of pretty prints.'],
            ['id' => 9, 'picture_Product' => 'product-09.jpg', 'name_Product' => 'Converse All Star Hi Plimsolls', 'price_Product' => 75.00, 'size_Product' => '40', 'color_Product' => 'Black', 'weight_Product' => '0.35 kg', 'dimensisons_Product' => '13 x 4 x 5 inches', 'materials_Product' => 'blank', 'description_Product' => 'The chuck taylor all star low top sneaker is the pioneer of laidback style, sporting the classic canvas upper and iconic silhouette. In soft, standout hues, this design has never been sweeter. Updated with a durable outsole. Ortholite insole for cushioning takes comfort to the next level. Ortholite is a trademark of O2 partners, llc.'],
            ['id' => 10, 'picture_Product' => 'product-10.jpg', 'name_Product' => 'Femme T-Shirt In Stripe', 'price_Product' => 25.85, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Cotton', 'description_Product' => 'Crafted from super-soft cotton jersey, the classic tee never gets old. Own one in every color for casual style, dressed up or down any day of the year.'],
            ['id' => 11, 'picture_Product' => 'product-11.jpg', 'name_Product' => 'Herschel shirt', 'price_Product' => 63.16, 'size_Product' => 'L', 'color_Product' => 'Blue', 'weight_Product' => '0.05 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '98% Cotton', 'description_Product' => 'Made from a lightweight cotton and elastane blend, this classic oxford shirt is the perfect staple with just the right amount of comfort stretch. Made with Organic Content Standard (OCS) 100 certified organic cotton and certified carbon neutral by ClimatePartner. Learn about our third party sustainability certifications below.'],
            ['id' => 12, 'picture_Product' => 'product-12.jpg', 'name_Product' => 'Herschel belt', 'price_Product' => 63.15, 'size_Product' => 'none', 'color_Product' => 'Brown', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 cm', 'materials_Product' => 'blank', 'description_Product' => ' This fashion belt is enclosed in a sleek and modern gift box, which make it a great gift for boyfriend, father and male colleagues as birthday gift or anniversary gift.'],
            ['id' => 13, 'picture_Product' => 'product-13.jpg', 'name_Product' => 'T-Shirt with Sleeve', 'price_Product' => 18.50, 'size_Product' => 'M', 'color_Product' => 'White', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Cotton', 'description_Product' => 'This Hanes Nano t-shirt for women is so light and soft you will fall in love with it. Ultra-light 100 percent ring-spun cotton jersey feels great on your skin and drapes beautifully.'],
            ['id' => 14, 'picture_Product' => 'product-14.jpg', 'name_Product' => 'Pretty Little Thing', 'price_Product' => 54.79, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.2 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '90% Cotton, 10% Polyester', 'description_Product' => 'Sometimes you want style. Other times you want comfort. The Gildan Softstyle Ladies’ T-Shirt offers both. Made from 4.5 oz. per sq. yd. fabric, this fitted silhouette jersey knit provides a fashionable look and soft feel that you’ll love the first time you put it on. With double-needle sleeve and bottom hems, and a high-stitch density, this durably constructed Tee also makes for a smooth printing surface.'],
            ['id' => 15, 'picture_Product' => 'product-15.jpg', 'name_Product' => 'Mini Silver Mesh Watch', 'price_Product' => 86.50, 'size_Product' => '36mm', 'color_Product' => 'Black', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '5 x 5 x 5 cm', 'materials_Product' => 'metal', 'description_Product' => 'The direct descendant of our 1960s televised torture test survivors, today is Easy Reader is as durable as it is classically cool.'],
            ['id' => 16, 'picture_Product' => 'product-16.jpg', 'name_Product' => 'Square Neck Back', 'price_Product' => 29.50, 'size_Product' => 'S', 'color_Product' => 'Gray', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '64% Polyester, 33% Rayon, 3% Spandex', 'description_Product' => 'We listen to customer feedback and fine-tune every detail to ensure our clothes are more comfortable, higher quality, and longer lasting—at affordable prices for the whole family.'],
        ]);
    }
}
